#! /usr/bin/ruby
# frozen_string_literal: true

if Dir.exist? "#{ENV['HOME']}/soulmate"
  puts "Oops - looks like you already have SoulmateZ installed at #{ENV['HOME']}/soulmate"
  puts 'Remove this Soulmate installation and reinstall? (y/N)'
  exit unless gets.rstrip == 'y'

  system("rm -rf #{ENV['HOME']}/soulmate/esp-idf")
  system("rm -rf #{ENV['HOME']}/soulmate/soulmate")
end

if Dir.glob('/usr/local/bin/pip').none?
  puts 'Installing pip'
  system('sudo easy_install pip')
end

puts 'Creating the ESP folder'
system("mkdir -p #{ENV['HOME']}/soulmate")

puts 'Installing ESP-IDF v3.3'
system("git clone -b release/v3.3 --recursive --recurse-submodules https://github.com/espressif/esp-idf.git #{ENV['HOME']}/soulmate/esp-idf")

puts 'Installing ESP-IDF requirements'
system("python -m pip install --user -r #{ENV['HOME']}/soulmate/esp-idf/requirements.txt")

puts 'Install Xtensa-ESP32-elf'
system("curl -o #{ENV['HOME']}/soulmate/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz https://dl.espressif.com/dl/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz")
system("tar -xzf #{ENV['HOME']}/soulmate/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz -C #{ENV['HOME']}/soulmate")
system("rm #{ENV['HOME']}/soulmate/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz")

puts 'Installing Soulmate...'
system("git clone --recursive --recurse-submodules https://github.com/Soulmate-Lights/soulmate-core.git #{ENV['HOME']}/soulmate/soulmate")

puts 'Done!'
puts 'To compile your Soulmate code, use ./run'
