#! /usr/bin/ruby
# frozen_string_literal: true

if Dir.exist? "#{ENV['HOME']}/soulmate"
  puts "Oops - looks like you already have Soulmate installed at #{ENV['HOME']}/soulmate"
  puts 'Remove this Soulmate installation and reinstall? (y/N)'
  exit unless gets.rstrip == 'y'

  system("rm -rf #{ENV['HOME']}/soulmate")
end

if Dir.glob('/usr/local/bin/pip').none?
  puts 'Installing pip'
  system('sudo easy_install pip')
end

puts 'Installing Soulmate...'
system("git clone --recursive --recurse-submodules https://github.com/Soulmate-Lights/soulmate-core.git #{ENV['HOME']}/soulmate")

puts 'Installing ESP-IDF requirements'
system("python -m pip install --user -r #{ENV['HOME']}/soulmate/esp-idf/requirements.txt")

system("open '#{ENV['HOME']}/soulmate/drivers/Install\ CP210x\ VCP\ Driver.app'")

puts 'Done!'
puts 'To compile your Soulmate code, use ./run'
