#! /usr/bin/ruby
# frozen_string_literal: true

require 'open3'
require 'etc'
cores = Etc.nprocessors - 1

ports = [
  '/dev/tty.wchusbserial*',
  '/dev/cu.SLAB_USBtoUART'
]

port = ports.map { |port| Dir.glob(port) }.flatten.first

command = "IDF_PATH=#{ENV['HOME']}/soulmate/esp-idf PATH=#{ENV['HOME']}/soulmate/xtensa-esp32-elf/bin:$PATH ESPPORT=#{port} make -j#{cores} flash"

unless port
  puts "Oops! I couldn't find an ESP32!"
  puts "Looked for these ports: #{ports.join(', ')}"
  exit
end

print "Compiling and uploading to #{port}"

Open3.popen3(command) do |_stdin, stdout, stderr, thread|
  putc '.' while stdout.gets

  puts

  if thread.value.zero?
    puts 'Your Soulmate is now online. Open your app to control it!'
  else
    puts 'Oops - something went wrong!'

    stderr.each_line do |line|
      puts line if line.include? 'error:'
    end
  end
end
