#! /usr/bin/ruby
# frozen_string_literal: true

port = Dir.glob('/dev/tty.wchusbserial*')[0]

unless port
  puts "Oops! I couldn't find an ESP32 at /dev/tty.wchusbserial*."
  puts 'Check the docs for more info.'
  exit
end

require 'etc'
cores = Etc.nprocessors - 1

puts "Compiling with #{cores} threads."

if system "IDF_PATH=~/esp/esp-idf PATH=$HOME/esp/xtensa-esp32-elf/bin:$PATH ESPPORT=#{port} make -j#{cores} flash"
  puts 'Your Soulmate is now online. Open your app to control it!'
else
  puts 'Oops - something went wrong!'
end
