#! /usr/bin/ruby
# frozen_string_literal: true

require 'open3'

require 'etc'
cores = Etc.nprocessors - 1

print "Compiling"

command = "IDF_PATH=~/esp/esp-idf PATH=$HOME/esp/xtensa-esp32-elf/bin:$PATH make -j#{cores}"

Open3.popen3(command) do |_stdin, stdout, stderr, thread|
  putc '.' while stdout.gets

  puts

  if thread.value == 0
    puts 'Build succeeded! Use ./run to flash this to your ESP32.'
  else
    puts 'Oops - something went wrong!'

    stderr.each_line do |line|
      puts line if line.include? 'error:'
    end
  end
end

